# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle for Iris 1.17+

on:
  push:
    branches: [ 1.14-1.16, actions ]
  pull_request:
    branches: [ 1.14-1.16, actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt-openj9'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Iris-WorldGen-master
        path: ./build/libs/*.jar
